import React from 'react';
import { ShieldCheck, Scale, AlertOctagon } from 'lucide-react';
import Link from 'next/link';

export function SecurityFooter() {
  return (
    <footer className="border-t border-zinc-100 bg-zinc-50/30 py-12 px-10">
      <div className="max-w-7xl mx-auto space-y-10">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-zinc-800 font-bold text-sm uppercase tracking-widest">
              <ShieldCheck size={16} className="text-brand-orange" /> Data Privacy
            </div>
            <p className="text-[11px] text-zinc-400 leading-relaxed font-medium uppercase tracking-tighter">
              We employ cryptographically secure hashing for all telemetry. IP addresses are anonymized before storage to ensure GDPR and CCPA compliance. No raw PII is ever persisted in our resolution nodes.
            </p>
          </div>

          <div className="space-y-4">
            <div className="flex items-center gap-2 text-zinc-800 font-bold text-sm uppercase tracking-widest">
              <Scale size={16} className="text-brand-orange" /> Legal Protocol
            </div>
            <p className="text-[11px] text-zinc-400 leading-relaxed font-medium uppercase tracking-tighter">
              By using QR Forge, you agree to our Terms of Service. Users are responsible for the content of their destination URLs. We maintain a zero-tolerance policy for phishing or malicious redirections.
            </p>
          </div>

          <div className="space-y-4">
            <div className="flex items-center gap-2 text-zinc-800 font-bold text-sm uppercase tracking-widest">
              <AlertOctagon size={16} className="text-brand-orange" /> Abuse Protection
            </div>
            <p className="text-[11px] text-zinc-400 leading-relaxed font-medium uppercase tracking-tighter">
              Detected abuse will result in immediate deactivation of the associated shortcode. To report a malicious link generated by our platform, please contact our security team at {process.env.NEXT_PUBLIC_CONTACT_EMAIL}.
            </p>
          </div>
        </div>

        <div className="pt-10 border-t border-zinc-100 flex flex-col md:flex-row justify-between items-center gap-6 opacity-40">
           <p className="font-bold text-[9px] text-zinc-500 uppercase tracking-[0.4em] text-center md:text-left">QRForge Protocol © 2026 // Operational Security Tier 1</p>
           <div className="flex flex-wrap justify-center gap-4 sm:gap-8 font-mono text-[9px] uppercase tracking-widest font-black text-center">
              <Link href="/legal/privacy" className="cursor-pointer hover:text-brand-orange transition-colors">Privacy Policy</Link>
              <Link href="/legal/terms" className="cursor-pointer hover:text-brand-orange transition-colors">Terms of Service</Link>
              <Link href="/legal/abuse" className="cursor-pointer hover:text-brand-orange transition-colors">Report Abuse</Link>
           </div>
        </div>
      </div>
    </footer>
  );
}
